import {
    Heart,
    SlidersHorizontal,
    Share2,
    Pin,
    Globe,
    HelpCircle,
    Venus,
    Ruler,
    Scale,
    Crosshair,
    Leaf,
    Cake,
    School,
    User,
    Baby,
    Cigarette,
    WineOff,
    PawPrint,
    Mars, 
    CheckCircle, // <-- Added for Verified icon
    X, // <-- Added for the Nope button
    Star, // <-- Added for Super Like button
} from "lucide-react";
const profiles = [
        // ... (your existing profile data for Tina and Marc) ...
        {
            id: 1,
            name: "Tina",
            age: 33,
            image: "https://images.pexels.com/photos/3775118/pexels-photo-3775118.jpeg?_gl=1*1slme73*_ga*MTMxOTk2NTc0OS4xNzU5Mjk3Nzg2*_ga_8JE65Q40S6*czE3NTkyOTc3ODYkbzEkZzEkdDE3NTkyOTc4NzAkajQxJGwwJGgw",
            about: "Mujer apasionada y profesional | Me encanta crecer cada día y rodearme de energía positiva | Disfruto de la paz... pero también de esos momentos intensos que se vuelven inolvidables",
            goal: "Find a relationship",
            location: "Anould, France",
            languages: ["Spanish"],
            basics: [
                { icon: <Venus className="icon" />, label: "Female" },
                { icon: <Ruler className="icon" />, label: "5'7\"" },
                { icon: <Scale className="icon" />, label: "142 lbs" },
                { icon: <Crosshair className="icon" />, label: "Heterosexual" },
                { icon: <Leaf className="icon" />, label: "Leo" },
                { icon: <Cake className="icon" />, label: "Sometimes" },
                { icon: <School className="icon" />, label: "Graduate degree" },
                { icon: <User className="icon" />, label: "Single" },
                { icon: <Baby className="icon" />, label: "Not yet" },
                { icon: <Cigarette className="icon" />, label: "Sometimes" },
                { icon: <WineOff className="icon" />, label: "Never" },
                { icon: <PawPrint className="icon" />, label: "Dogs" },
            ],
            interests: [
                "✍️ Poetry", "🎵 Music", "📷 Photography", "📖 Reading", "📺 TV", 
                "🚗 Cars", "⚾ Baseball", "⚽ Football", "🏎️ Formula 1", "🎵 Latin American music", 
                "🎵 Electronic music", "🎵 Rock", "🎵 Reggae", "🎵 Pop", "🐶 Dogs",
            ],
        },
        {
            id: 2,
            name: "Marc",
            age: 28,
            image: "https://images.unsplash.com/photo-1549068106-b024baf5062d?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1974&q=80", 
            about: "Software engineer who loves mountains and craft beer 🍺. Looking for someone to hike with.",
            goal: "Looking for fun",
            location: "Paris, France",
            languages: ["English", "French"],
            basics: [
                { icon: <Mars className="icon" />, label: "Male" },
                { icon: <Ruler className="icon" />, label: "6'1\"" },
                { icon: <Scale className="icon" />, label: "185 lbs" },
                { icon: <Crosshair className="icon" />, label: "Heterosexual" },
                { icon: <Leaf className="icon" />, label: "Gemini" },
                { icon: <Cake className="icon" />, label: "Often" },
                { icon: <School className="icon" />, label: "Bachelors" },
                { icon: <User className="icon" />, label: "Single" },
                { icon: <Cigarette className="icon" />, label: "Never" },
                { icon: <WineOff className="icon" />, label: "Sometimes" },
                { icon: <PawPrint className="icon" />, label: "Cats" },
            ],
            interests: [
                "💻 Coding", "⛰️ Hiking", "🍺 Craft Beer", "🎸 Guitar", "🎮 Gaming", 
                "⚽ Football", "🎵 Jazz", "📚 History", "✈️ Travel", "🐶 Dogs",
            ],
        },
        // --- NEW PROFILES START HERE ---
        {
            id: 3,
            name: "Sofia",
            age: 26,
            image: "https://images.pexels.com/photos/1468379/pexels-photo-1468379.jpeg?_gl=1*krcqmv*_ga*MTMxOTk2NTc0OS4xNzU5Mjk3Nzg2*_ga_8JE65Q40S6*czE3NTk1ODkwMTYkbzIkZzEkdDE3NTk1ODkxNDEkajU5JGwwJGgw",
            about: "Digital nomad 🌎. I love exploring new cities, trying local food, and finding the best coffee shops. Looking for someone spontaneous and fun!",
            goal: "Looking for fun",
            location: "Berlin, Germany",
            languages: ["English", "German", "Portuguese"],
            basics: [
                { icon: <Venus className="icon" />, label: "Female" },
                { icon: <Ruler className="icon" />, label: "5'4\"" },
                { icon: <Scale className="icon" />, label: "125 lbs" },
                { icon: <Crosshair className="icon" />, label: "Heterosexual" },
                { icon: <Leaf className="icon" />, label: "Sagittarius" },
                { icon: <Cake className="icon" />, label: "Often" },
                { icon: <School className="icon" />, label: "Bachelors" },
                { icon: <User className="icon" />, label: "Single" },
                { icon: <Baby className="icon" />, label: "Want to" },
                { icon: <Cigarette className="icon" />, label: "Never" },
                { icon: <WineOff className="icon" />, label: "Socially" },
                { icon: <PawPrint className="icon" />, label: "Neither" },
            ],
            interests: [
                "✈️ Travel", "☕ Coffee", "🍜 Cooking", "🧘 Yoga", "📚 Self-Improvement", 
                "🎵 Pop", "💃 Dancing", "🎭 Theatre", "🎨 Art", "📸 Vlogging",
            ],
        },
        {
            id: 4,
            name: "Cindy",
            age: 31,
            image: "https://images.pexels.com/photos/1587009/pexels-photo-1587009.jpeg?_gl=1*299y5q*_ga*MTMxOTk2NTc0OS4xNzU5Mjk3Nzg2*_ga_8JE65Q40S6*czE3NTk1ODkwMTYkbzIkZzEkdDE3NTk1ODkxMjkkajExJGwwJGgw",
            about: "Architect by day, musician by night 🎸. I value honesty and a good sense of humor. Let's grab a drink and see where the conversation goes.",
            goal: "Find a relationship",
            location: "New York, USA",
            languages: ["English"],
            basics: [
                { icon: <Mars className="icon" />, label: "Male" },
                { icon: <Ruler className="icon" />, label: "5'10\"" },
                { icon: <Scale className="icon" />, label: "175 lbs" },
                { icon: <Crosshair className="icon" />, label: "Bisexual" },
                { icon: <Leaf className="icon" />, label: "Libra" },
                { icon: <Cake className="icon" />, label: "Often" },
                { icon: <School className="icon" />, label: "Graduate degree" },
                { icon: <User className="icon" />, label: "Divorced" },
                { icon: <Baby className="icon" />, label: "Have and want more" },
                { icon: <Cigarette className="icon" />, label: "Sometimes" },
                { icon: <WineOff className="icon" />, label: "Never" },
                { icon: <PawPrint className="icon" />, label: "Dogs" },
            ],
            interests: [
                "🎵 Music Production", "🏛️ Architecture", "📖 Reading", "🍜 Cooking", "🎾 Tennis",
                "🍻 Bar-hopping", "🎨 Art", "🎵 Rock", "🎵 Jazz", "🐶 Dogs",
            ],
        },
        {
            id: 5,
            name: "Clara",
            age: 24,
            image: "https://images.pexels.com/photos/1130626/pexels-photo-1130626.jpeg?_gl=1*1hv9v85*_ga*MTMxOTk2NTc0OS4xNzU5Mjk3Nzg2*_ga_8JE65Q40S6*czE3NTk1ODkwMTYkbzIkZzEkdDE3NTk1ODkwOTQkajQ2JGwwJGgw",
            about: "Student and part-time baker 🍰. Always up for a last-minute adventure. Hoping to find someone to share my dessert creations with!",
            goal: "Find a relationship",
            location: "London, UK",
            languages: ["English", "Spanish"],
            basics: [
                { icon: <Venus className="icon" />, label: "Female" },
                { icon: <Ruler className="icon" />, label: "5'6\"" },
                { icon: <Scale className="icon" />, label: "135 lbs" },
                { icon: <Crosshair className="icon" />, label: "Heterosexual" },
                { icon: <Leaf className="icon" />, label: "Aries" },
                { icon: <Cake className="icon" />, label: "Socially" },
                { icon: <School className="icon" />, label: "Some college" },
                { icon: <User className="icon" />, label: "Single" },
                { icon: <Baby className="icon" />, label: "Not yet" },
                { icon: <Cigarette className="icon" />, label: "Never" },
                { icon: <WineOff className="icon" />, label: "Sometimes" },
                { icon: <PawPrint className="icon" />, label: "Cats" },
            ],
            interests: [
                "🍰 Baking", "🎨 Drawing", "📺 Movies", "✈️ Travel", "🏃 Running",
                "🎵 Pop", "📚 Fiction", "🛍️ Shopping", "📸 Photography", "🎮 Puzzles",
            ],
        },
        {
            id: 6,
            name: "Ethan",
            age: 37,
            image: "https://images.pexels.com/photos/774909/pexels-photo-774909.jpeg?_gl=1*sme66i*_ga*MTMxOTk2NTc0OS4xNzU5Mjk3Nzg2*_ga_8JE65Q40S6*czE3NTk1ODkwMTYkbzIkZzEkdDE3NTk1ODkwODAkajYwJGwwJGgw",
            about: "Marketing executive and outdoor enthusiast. I'm a morning person who loves kayaking and is looking for a meaningful connection.",
            goal: "Find a relationship",
            location: "Vancouver, Canada",
            languages: ["English"],
            basics: [
                { icon: <Mars className="icon" />, label: "Male" },
                { icon: <Ruler className="icon" />, label: "6'0\"" },
                { icon: <Scale className="icon" />, label: "190 lbs" },
                { icon: <Crosshair className="icon" />, label: "Heterosexual" },
                { icon: <Leaf className="icon" />, label: "Capricorn" },
                { icon: <Cake className="icon" />, label: "Sometimes" },
                { icon: <School className="icon" />, label: "Masters" },
                { icon: <User className="icon" />, label: "Widowed" },
                { icon: <Baby className="icon" />, label: "Have but don't want more" },
                { icon: <Cigarette className="icon" />, label: "Never" },
                { icon: <WineOff className="icon" />, label: "Socially" },
                { icon: <PawPrint className="icon" />, label: "Dogs" },
            ],
            interests: [
                "🛶 Kayaking", "🏞️ Camping", "📈 Finance", "📰 News", "🚴 Cycling",
                "🍻 Craft Beer", "🎵 Blues", "📚 Biographies", "🐶 Dogs", "🍲 Fine Dining",
            ],
        },
    ];

    export default profiles;