"""Change ProfileInterest.interest_name to interest_id

Revision ID: b986f2985e7f
Revises: 66826e92386a
Create Date: 2025-11-02 15:20:33.470860

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy.sql import table, column, select

# revision identifiers, used by Alembic.
revision: str = 'b986f2985e7f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # --- ONLY KEEP THIS BLOCK FOR profile_interests ---
    with op.batch_alter_table('profile_interests', schema=None) as batch_op:
        # 1. Add the new interest_id column (nullable temporarily)
        batch_op.add_column(sa.Column('interest_id', sa.Integer(), nullable=True))

    # 2. Perform data migration: Populate interest_id based on interest_name
    profile_interests_table = table(
        'profile_interests',
        column('id', sa.Integer),
        column('interest_name', sa.String),
        column('interest_id', sa.Integer)
    )
    interests_table = table(
        'interests',
        column('id', sa.Integer),
        column('name', sa.String)
    )

    connection = op.get_bind()
    profile_interests_data = connection.execute(select(profile_interests_table.c.id, profile_interests_table.c.interest_name)).fetchall()

    ids_to_delete = [] # Collect IDs of records that cannot be mapped

    for pi_id, pi_name in profile_interests_data:
        interest_id_result = connection.execute(
            select(interests_table.c.id).where(interests_table.c.name == pi_name)
        ).scalar_one_or_none()

        if interest_id_result:
            connection.execute(
                profile_interests_table.update().
                where(profile_interests_table.c.id == pi_id).
                values(interest_id=interest_id_result)
            )
        else:
            print(f"Warning: Interest '{pi_name}' not found in 'interests' table for profile_interest ID {pi_id}. This record will be DELETED.")
            ids_to_delete.append(pi_id)

    # Delete records that could not be mapped
    if ids_to_delete:
        connection.execute(
            profile_interests_table.delete().
            where(profile_interests_table.c.id.in_(ids_to_delete))
        )
        print(f"Deleted {len(ids_to_delete)} profile_interests records with unmatchable interest_names.")


    # 3. Make the interest_id column NOT NULL (after data is populated and unmatchable records deleted)
    with op.batch_alter_table('profile_interests', schema=None) as batch_op:
        batch_op.alter_column('interest_id', existing_type=sa.Integer(), nullable=False)

    # 4. Add the foreign key constraint
    with op.batch_alter_table('profile_interests', schema=None) as batch_op:
        batch_op.create_foreign_key(op.f('fk_profile_interests_interest_id_interests'), 'interests', ['interest_id'], ['id'])

    # 5. Drop the old interest_name column
    with op.batch_alter_table('profile_interests', schema=None) as batch_op:
        batch_op.drop_column('interest_name')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # --- ONLY KEEP THIS BLOCK FOR profile_interests ---
    profile_interests_table = table(
        'profile_interests',
        column('id', sa.Integer),
        column('interest_name', sa.String), # Will be added
        column('interest_id', sa.Integer) # Will be dropped
    )
    interests_table = table(
        'interests',
        column('id', sa.Integer),
        column('name', sa.String)
    )

    connection = op.get_bind()

    with op.batch_alter_table('profile_interests', schema=None) as batch_op:
        # 1. Add the interest_name column (temporarily nullable)
        batch_op.add_column(sa.Column('interest_name', sa.VARCHAR(length=50), autoincrement=False, nullable=True))

    # 2. Perform data migration: Populate interest_name from interest_id
    profile_interests_data = connection.execute(
        select(profile_interests_table.c.id, profile_interests_table.c.interest_id)
    ).fetchall()

    for pi_id, pi_interest_id in profile_interests_data:
        if pi_interest_id:
            interest_name_result = connection.execute(
                select(interests_table.c.name).where(interests_table.c.id == pi_interest_id)
            ).scalar_one_or_none()

            if interest_name_result:
                connection.execute(
                    profile_interests_table.update().
                    where(profile_interests_table.c.id == pi_id).
                    values(interest_name=interest_name_result)
                )
            else:
                print(f"Warning: interest_id {pi_interest_id} not found in 'interests' table for profile_interest ID {pi_id}. interest_name will remain NULL.")
        else:
            print(f"Warning: interest_id is NULL for profile_interest ID {pi_id}. interest_name will remain NULL.")

    # 3. Make interest_name NOT NULL (assuming it was originally NOT NULL)
    with op.batch_alter_table('profile_interests', schema=None) as batch_op:
        batch_op.alter_column('interest_name', existing_type=sa.VARCHAR(length=50), nullable=False)

    # 4. Drop the foreign key constraint
    with op.batch_alter_table('profile_interests', schema=None) as batch_op:
        batch_op.drop_constraint(op.f('fk_profile_interests_interest_id_interests'), type_='foreignkey')

    # 5. Drop the interest_id column
    with op.batch_alter_table('profile_interests', schema=None) as batch_op:
        batch_op.drop_column('interest_id')

    # ### end Alembic commands ###



